import type { Metadata } from "next";

interface PageProps {
  params: Promise<{ locale: string }>;
}

export async function generateMetadata({ params }: PageProps): Promise<Metadata> {
  const { locale } = await params;
  const isKo = locale === "ko";
  return {
    title: isKo ? "개인정보처리방침" : "Privacy Policy",
    description: isKo
      ? "리파인주식회사 개인정보처리방침"
      : "Refind Inc. Privacy Policy",
  };
}

const EFFECTIVE_DATE = { ko: "2026년 8월 7일", en: "August 7, 2026" };

const SECTIONS_KO = [
  {
    title: "1. 수집하는 개인정보의 항목 및 수집 방법",
    body: [
      "리파인주식회사(이하 '회사')는 일반 이용자를 대상으로 하는 회원가입 및 게시판 기능을 운영하지 않으며, 홈페이지를 통해 이용자로부터 직접 개인정보를 수집하지 않습니다.",
      "다만 다음의 경우에 한해 아래와 같은 정보가 처리됩니다.",
      "· 관리자(운영자) 로그인: 이메일, 비밀번호(암호화 저장) — 공지사항·카드뉴스 게시물 관리를 위해 회사 임직원 계정에 한해 발급되며, 외부 이용자는 가입할 수 없습니다.",
      "· 자동 수집 정보: 서비스 이용 과정에서 IP 주소, 접속 일시, 브라우저 정보 등 접속 로그가 서버에 자동으로 생성·보관됩니다.",
      "· 문의: 사이트의 '문의하기' 메뉴는 회사가 운영하는 네이버폼(네이버 주식회사 제공 외부 서비스)의 새 창으로 연결됩니다. 문의 시 입력하는 이름, 이메일, 연락처, 문의 내용 등은 홈페이지가 아닌 네이버의 서버에 직접 수집·저장되며, 네이버의 개인정보처리방침이 적용됩니다.",
    ],
  },
  {
    title: "2. 개인정보의 수집 및 이용 목적",
    body: [
      "· 관리자 계정 정보: 관리자 인증 및 게시물 관리 권한 확인",
      "· 접속 로그: 서비스 부정 이용 방지, 서버 보안 유지 및 장애 대응",
      "· 문의 내용(네이버폼): 문의 확인 및 답변",
    ],
  },
  {
    title: "3. 개인정보의 보유 및 이용기간",
    body: [
      "· 관리자 계정 정보: 해당 임직원의 관리자 권한이 유지되는 동안 보관하며, 권한 해지 시 지체 없이 파기합니다.",
      "· 접속 로그: 통신비밀보호법 등 관계 법령에 따라 3개월간 보관 후 파기합니다.",
      "· 네이버폼을 통해 접수된 문의 정보는 회사가 직접 보관하지 않으며, 네이버의 정책에 따라 관리됩니다.",
    ],
  },
  {
    title: "4. 개인정보의 제3자 제공",
    body: [
      "회사는 이용자의 개인정보를 원칙적으로 외부에 제공하지 않습니다. 다만 문의는 이용자가 네이버폼을 통해 직접 네이버에 정보를 제공하는 방식으로 이루어지며, 회사는 답변 목적으로만 해당 문의 내용을 확인합니다.",
    ],
  },
  {
    title: "5. 개인정보처리의 위탁",
    body: [
      "회사는 서비스 운영을 위해 다음과 같이 업무를 위탁하고 있습니다.",
      "· Supabase Inc. — 데이터베이스 및 이미지 파일 클라우드 저장",
      "· 네이버 주식회사 — 문의 접수용 폼(네이버폼) 서비스 운영",
    ],
  },
  {
    title: "6. 정보주체의 권리·의무 및 행사방법",
    body: [
      "이용자는 회사가 보유한 자신의 개인정보(관리자 계정 정보 등)에 대해 열람, 정정, 삭제, 처리정지를 요청할 수 있으며, 하단의 연락처로 문의하시면 지체 없이 조치합니다. 네이버폼을 통해 제공한 정보에 관한 권리 행사는 네이버의 절차를 따릅니다.",
    ],
  },
  {
    title: "7. 쿠키(Cookie)의 운용",
    body: [
      "홈페이지는 방문자를 대상으로 한 광고성·분석용 쿠키를 사용하지 않습니다. 관리자 로그인 시 인증 상태 유지를 위한 필수 세션 쿠키만 사용되며, 이는 일반 이용자에게는 적용되지 않습니다.",
    ],
  },
  {
    title: "8. 개인정보의 안전성 확보조치",
    body: [
      "· 관리자 비밀번호는 암호화(bcrypt)하여 저장하며, 관리자 기능은 인증된 계정만 접근할 수 있도록 접근 권한을 제한합니다.",
      "· 홈페이지와 서버 간 통신은 HTTPS로 암호화되어 전송됩니다.",
    ],
  },
  {
    title: "9. 개인정보 보호책임자",
    body: [
      "회사는 개인정보 처리에 관한 업무를 총괄하고 이용자의 불만 처리 및 피해 구제를 위해 아래와 같이 담당 부서를 지정하고 있습니다.",
      "· 회사명: 리파인주식회사",
      "· 전화: 070-4837-2829",
      "· 이메일: refind@refind.kr",
    ],
  },
  {
    title: "10. 고지의 의무",
    body: [
      "이 개인정보처리방침은 법령·정책 또는 서비스 변경에 따라 내용이 추가·삭제·수정될 수 있으며, 변경 시 홈페이지를 통해 공지합니다.",
      `본 방침은 ${EFFECTIVE_DATE.ko}부터 적용됩니다.`,
    ],
  },
];

const SECTIONS_EN = [
  {
    title: "1. Personal Information Collected and Collection Methods",
    body: [
      "Refind Inc. (the \"Company\") does not operate a public sign-up or community board on this website, and does not collect personal information directly from general visitors.",
      "Information is processed only in the following limited cases.",
      "· Administrator login: email and password (stored encrypted) — issued solely to Company staff for managing Notice and Card News posts. External users cannot register an account.",
      "· Automatically collected information: access logs such as IP address, access time, and browser information generated by the server while using the site.",
      "· Inquiries: the \"Inquiry\" menu links to an external Naver Form (a service provided by NAVER Corporation) in a new tab. Any name, email, phone number, or message entered there is collected and stored directly by NAVER, not by this website, and is governed by NAVER's own privacy policy.",
    ],
  },
  {
    title: "2. Purpose of Collection and Use",
    body: [
      "· Administrator account information: authenticating administrators and verifying content-management permissions",
      "· Access logs: preventing misuse of the service, maintaining server security, and responding to incidents",
      "· Inquiry content (via Naver Form): reviewing and responding to inquiries",
    ],
  },
  {
    title: "3. Retention Period",
    body: [
      "· Administrator account information: retained while the staff member's administrator role remains active, and destroyed without delay upon revocation.",
      "· Access logs: retained for 3 months in accordance with applicable law (e.g. the Protection of Communications Secrets Act), then destroyed.",
      "· Inquiry information submitted via Naver Form is not stored by the Company and is managed according to NAVER's policies.",
    ],
  },
  {
    title: "4. Provision to Third Parties",
    body: [
      "The Company does not provide personal information to third parties in principle. Inquiries are submitted directly to NAVER by the user via Naver Form, and the Company only reviews that content for the purpose of responding.",
    ],
  },
  {
    title: "5. Outsourcing of Personal Information Processing",
    body: [
      "The Company outsources the following operations:",
      "· Supabase, Inc. — cloud database and image file storage",
      "· NAVER Corporation — operation of the inquiry form (Naver Form)",
    ],
  },
  {
    title: "6. Rights of Data Subjects",
    body: [
      "Users may request access to, correction of, deletion of, or suspension of processing of their personal information held by the Company (e.g. administrator account information) by contacting the address below; the Company will act without delay. Rights relating to information submitted via Naver Form follow NAVER's own procedures.",
    ],
  },
  {
    title: "7. Use of Cookies",
    body: [
      "This website does not use advertising or analytics cookies for visitors. Only an essential session cookie for maintaining login state is used during administrator login, and it does not apply to general visitors.",
    ],
  },
  {
    title: "8. Security Measures",
    body: [
      "· Administrator passwords are stored encrypted (bcrypt), and access to administrator functions is restricted to authenticated accounts.",
      "· Communication between the website and server is encrypted via HTTPS.",
    ],
  },
  {
    title: "9. Personal Information Protection Officer",
    body: [
      "The Company designates the following contact for matters concerning personal information processing and for handling user complaints and requests.",
      "· Company: Refind Inc.",
      "· Phone: 070-4837-2829",
      "· Email: refind@refind.kr",
    ],
  },
  {
    title: "10. Notice of Changes",
    body: [
      "This privacy policy may be amended to reflect changes in law, policy, or the service, and any changes will be announced on this website.",
      `This policy is effective as of ${EFFECTIVE_DATE.en}.`,
    ],
  },
];

export default async function PrivacyPage({ params }: PageProps) {
  const { locale } = await params;
  const isKo = locale === "ko";
  const sections = isKo ? SECTIONS_KO : SECTIONS_EN;

  return (
    <div className="pt-16">
      <section className="bg-gradient-to-br from-gray-900 to-gray-800 py-24">
        <div className="max-w-3xl mx-auto px-6">
          <h1 className="text-4xl font-bold text-white mb-3">
            {isKo ? "개인정보처리방침" : "Privacy Policy"}
          </h1>
          <p className="text-gray-400">
            {isKo ? "리파인주식회사" : "Refind Inc."}
          </p>
        </div>
      </section>

      <section className="py-16 bg-white">
        <div className="max-w-3xl mx-auto px-6 prose prose-sm sm:prose-base prose-headings:font-bold prose-headings:text-gray-900 text-gray-700">
          {sections.map((section) => (
            <div key={section.title} className="mb-10">
              <h2>{section.title}</h2>
              {section.body.map((line, i) => (
                <p key={i}>{line}</p>
              ))}
            </div>
          ))}
        </div>
      </section>
    </div>
  );
}
